---
driver:
  name: vagrant
  vm_hostname: false
  vagrantfiles:
    - ./test/.Vagrantfile.cachier.rb

provisioner:
  name: chef_solo
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
<% [6,7].each do |centos_version| %>
  - name: centos-<%=centos_version%>-chef-12.8
    driver:
      box: inviqa/centos-<%=centos_version%>-minimal
    provisioner:
      require_chef_omnibus: "12.8"
<% end %>
  - name: centos-6-chef-11.18
    driver:
      box: inviqa/centos-6-minimal
    provisioner:
      require_chef_omnibus: "11.18"

suites:
  - name: default
    data_bags_path: "test/data_bags"
    run_list:
      - recipe[deploy-user::default]
    attributes:
      capistrano:
        user_data_bag_encrypted: false
